on: push
      
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
          version: [latest,release-v5.3,release-v5.1,release-v5.2,release-v5.0,v5.0.7,v5.3,v5.3-rc1,release-v4.4,v4.4.8,v5.3-beta2,v5.2.2,release-v4.3,v5.3-beta1,v5.1.4,v5.4-dev,v5.2.1,v4.4.7,v5.1.3,v5.0.6,v5.2,v5.2-rc1,v5.0.5,v4.3.7,v5.2-beta2,v5.1.2,v4.4.6,v5.0.4,v4.3.6,v5.1.1,v5.0.3,v5.1,release-v4.2,v4.2.5,v5.1-rc2,v4.4.5,v5.1-rc1,v5.1-beta1,v5.0.2,v5.2-dev,v4.3.5,v5.0.1,v4.4.4,release-v4.1,v4.1.4,v5.0,v5.0-rc1,v4.4.3,v4.3.4,v4.2.4,v5.0-beta1,v5.1-dev,v4.4.2,v4.3.3,v4.1.3,v4.4.1,v4.2.3,release-v3.3,v3.3.6,v4.4,v4.3.2,v4.0.4,release-v4.0,v4.3.1,v4.1.2,v4.2.2,v3.3.5,v4.3,v4.2.1,v4.1.1,v4.2,v4.0.2,v3.3.4,v3.3.3,v4.1,v3.3.2,v3.3.1,]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ matrix.version }}
        target: esp32c3
        path: '.'